### ISSUE TITLE
QA_Virtual Memory_Prerequisites_p1

### ISSUE THREAD

**Issue by kolliSuman** [virtual-labs/computer-organization-iiith#32]
Defect Description :
In the "Virtual Memory " experiment, the minimum requirement to run the experiment is not displayed in the page instead a page or Scrolling should appear providing information on minimum requirement to run this experiment, information like Bandwidth,Device Resolution,Hardware Configuration and Software Required.

Actual Result :
In the "Virtual Memory " experiment, the minimum requirement to run the experiment is not displayed in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-organization-iiith/blob/master/test-cases/integration_test-cases/Virtual%20Memory/Virtual%20Memory_13_Prerequisites_p1.org

Attachment:
![cso21](https://cloud.githubusercontent.com/assets/14869397/14778750/5f94338a-0af2-11e6-93be-9f691f3f758a.png)

**Comment by sravanthimodepu** [comment]
This issue is differed. Hence closing the issue.

**Comment by BSravanthi** [comment]
Issue is closed.
