### ISSUE TITLE
QA_Virtual Memory_Back to experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [virtual-labs/computer-organization-iiith#33]
Defect Description :
In the "Virtual Memory " experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen in-order to view the list of experiments by the user.

Actual Result :
In the "Virtual Memory " experiment,the back to experiments link is not present in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-organization-iiith/blob/master/test-cases/integration_test-cases/Virtual%20Memory/Virtual%20Memory_12_Back%20to%20experiment_smk.org

Attachment:
![cso20](https://cloud.githubusercontent.com/assets/14869397/14778763/6f54e968-0af2-11e6-9030-b546b5f8c140.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Issue is fixed.
