### ISSUE TITLE
QA_Virtual Memory_Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [virtual-labs/computer-organization-iiith#34]
Defect Description :
When we click on the feedback link in the feedback page of "Virtual Memory" experiment, it is redirecting to an error page(404) instead it should redirect to the feedback page.

Actual Result :
When we click on the feedback link of "Virtual Memory" experiment, it is redirecting to an error page(404).

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-organization-iiith/blob/master/test-cases/integration_test-cases/Virtual%20Memory/Virtual%20Memory_10_Feedback_smk.org

Attachment:
![cso19](https://cloud.githubusercontent.com/assets/14869397/14778773/80d34ad6-0af2-11e6-9150-35b5ecf425cb.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Issue is fixed.
