### ISSUE TITLE
QA_Cache Organizations_Back to experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [virtual-labs/computer-organization-iiith#37]
Defect Description :
In the "Cache Organizations " experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen in-order to view the list of experiments by the user.

Actual Result :
In the "Cache Organizations " experiment,the back to experiments link is not present in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-organization-iiith/blob/master/test-cases/integration_test-cases/Cache%20Organizations/Cache%20Organizations_19_Back%20to%20experiment_smk.org

Attachment:
![cso16](https://cloud.githubusercontent.com/assets/14869397/14778881/0fedc26e-0af3-11e6-8b83-0fe1690fb00f.png)

**Comment by sravanthimodepu** [comment]
This experiment doesn't have source code, so this experiment was removed from the lab.
Hence differing this issue.

**Comment by BSravanthi** [comment]
Issue is closed.
