### ISSUE TITLE
QA_Cache Organizations_Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [virtual-labs/computer-organization-iiith#38]
Defect Description :
When we click on the feedback link in the feedback page of "Cache Organizations" experiment, it is redirecting to an error page(404) instead it should redirect to the feedback page.

Actual Result :
When we click on the feedback link of "Cache Organizations" experiment, it is redirecting to an error page(404).

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-organization-iiith/blob/master/test-cases/integration_test-cases/Cache%20Organizations/Cache%20Organizations_17_Feedback_smk.org

Attachment:
![cso15](https://cloud.githubusercontent.com/assets/14869397/14778899/2e94a0f2-0af3-11e6-85c4-6c3a077ae01a.png)

**Comment by sravanthimodepu** [comment]
This experiment doesn't have source code, so this experiment was removed from the lab.
Hence differing this issue.

**Comment by BSravanthi** [comment]
Issue is closed.
