### ISSUE TITLE
QA_Single Cycle MIPS CPU_Prerequisites_p1

### ISSUE THREAD

**Issue by kolliSuman** [virtual-labs/computer-organization-iiith#4]
Defect Description :
In the "Single Cycle MIPS CPU  " experiment, the minimum requirement to run the experiment is not displayed in the page instead a page or Scrolling should appear providing information on minimum requirement to run this experiment, information like Bandwidth,Device Resolution,Hardware Configuration and Software Required.

Actual Result :
In the "Single Cycle MIPS CPU  " experiment, the minimum requirement to run the experiment is not displayed in the page.

Environment :
OS: Windows 7,Linux
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-organization-iiith/blob/master/test-cases/integration_test-cases/Single%20Cycle%20MIPS%20CPU/Single%20Cycle%20MIPS%20CPU_13_Prerequisites_p1.org

Attachment:
![cso49](https://cloud.githubusercontent.com/assets/14869397/14776583/08cb8d30-0ae5-11e6-9081-7d3654062f98.png)

**Comment by sravanthimodepu** [comment]
This issue is differed.

**Comment by BSravanthi** [comment]
Issue is closed.
