### ISSUE TITLE
QA_Representation of Floating Point Numbers and their Arithmetic_Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [virtual-labs/computer-organization-iiith#43]
Defect Description :
When we click on the feedback link in the feedback page of "Representation of Floating Point Numbers and their Arithmetic" experiment, it is redirecting to an error page(404) instead it should redirect to the feedback page.

Actual Result :
When we click on the feedback link of "Representation of Floating Point Numbers and their Arithmetic" experiment, it is redirecting to an error page(404).

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-organization-iiith/blob/master/test-cases/integration_test-cases/Representation%20of%20Floating%20Point%20Numbers%20and%20their%20Arithmetic/Representation%20of%20Floating%20Point%20Numbers%20and%20their%20Arithmetic_15_Feedback_smk.org

Attachment:
![cso10](https://cloud.githubusercontent.com/assets/14869397/14779022/b9ac488e-0af3-11e6-8f8f-1cc3f33557e3.png)

**Comment by sravanthimodepu** [comment]
Issued is fixed now.

**Comment by BSravanthi** [comment]
Issue is closed.
