### ISSUE TITLE
QA_Representation of Floating Point Numbers and their Arithmetic_Experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [virtual-labs/computer-organization-iiith#45]
Defect Description :
In the Experiment page of " Representation of Floating Point Numbers and their Arithmetic " experiment, when we click on the “Click here” link, a pop-up box with the download options is displaying on the screen instead it should redirect to the simulation page in-order to perform the simulation for the experiment

Actual Result :
In the Experiment page of " Representation of Floating Point Numbers and their Arithmetic " experiment, when we click on the “Click here” link, a pop-up box with the download options is displaying on the screen

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-organization-iiith/blob/master/test-cases/integration_test-cases/Representation%20of%20Floating%20Point%20Numbers%20and%20their%20Arithmetic/Representation%20of%20Floating%20Point%20Numbers%20and%20their%20Arithmetic_05_Experiment_smk.org

Attachment:
![cso8](https://cloud.githubusercontent.com/assets/14869397/14779057/ebce50fa-0af3-11e6-870f-fd60d34a3cd7.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Issue is closed.
