### ISSUE TITLE
QA_Representation of Floating Point Numbers and their Arithmetic_Experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [virtual-labs/computer-organization-iiith#46]
Defect Description :
In the Experiment page of "Representation of Floating Point Numbers and their Arithmetic" experiment, the next and previous symbols are placed for submit and reset buttons respectively instead the next and previous symbols should be removed

Actual Result :
In the Experiment page of "Representation of Floating Point Numbers and their Arithmetic" experiment, the next and previous symbols are placed for submit and reset buttons respectively

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-organization-iiith/blob/master/test-cases/integration_test-cases/Representation%20of%20Floating%20Point%20Numbers%20and%20their%20Arithmetic/Representation%20of%20Floating%20Point%20Numbers%20and%20their%20Arithmetic_05_Experiment_smk.org

Attachment:
![cso7](https://cloud.githubusercontent.com/assets/14869397/14779074/f8f60458-0af3-11e6-9109-fb7d679def08.png)

**Comment by sravanthimodepu** [comment]
The issue is in flash file and as we are not fixing the bugs in flash version of lab as of now. This issue will be resolved once lab gets converted from from flash to JavaScript. But till then this issue will persist in this version. So hereby differing the issue.

**Comment by BSravanthi** [comment]
Issue is closed.
