### ISSUE TITLE
QA_Representation of Integers and their Arithmetic_Prerequisites_p1

### ISSUE THREAD

**Issue by kolliSuman** [virtual-labs/computer-organization-iiith#47]
Defect Description :
In the "Representation of Integers and their Arithmetic" experiment, the minimum requirement to run the experiment is not displayed in the page instead a page or Scrolling should appear providing information on minimum requirement to run this experiment, information like Bandwidth,Device Resolution,Hardware Configuration and Software Required.

Actual Result :
In the "Representation of Integers and their Arithmetic" experiment, the minimum requirement to run the experiment is not displayed in the page.

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-organization-iiith/blob/master/test-cases/integration_test-cases/Representation%20of%20Integers%20and%20their%20Arithmetic/Representation%20of%20Integers%20and%20their%20Arithmetic_18_Prerequisites_p1.org

Attachment:
![cso6](https://cloud.githubusercontent.com/assets/14869397/14779108/15baf83c-0af4-11e6-830a-b867b7217a29.png)

**Comment by sravanthimodepu** [comment]
This issue is differed. Hence closing the issue.

**Comment by BSravanthi** [comment]
Issue is closed.
