### ISSUE TITLE
QA_Representation of Integers and their Arithmetic_Back to experiment_p1

### ISSUE THREAD

**Issue by kolliSuman** [virtual-labs/computer-organization-iiith#48]
Defect Description :
In the "Representation of Integers and their Arithmetic" experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen in-order to view the list of experiments by the user.

Actual Result :
In the "Representation of Integers and their Arithmetic" experiment,the back to experiments link is not present in the page..

Environment :
OS: Windows 7, Ubuntu-16.04,Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-organization-iiith/blob/master/test-cases/integration_test-cases/Representation%20of%20Integers%20and%20their%20Arithmetic/Representation%20of%20Integers%20and%20their%20Arithmetic_17_Back%20to%20experiment_p1.org

Attachment:
![cso5](https://cloud.githubusercontent.com/assets/14869397/14779118/2384d780-0af4-11e6-99f7-e0be89d31a19.png)

**Comment by sravanthimodepu** [comment]
Issued is fixed now.

**Comment by BSravanthi** [comment]
Issue is closed.
