### ISSUE TITLE
QA_Single Cycle MIPS CPU_Back to experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [virtual-labs/computer-organization-iiith#5]
Defect Description :
In the "Single Cycle MIPS CPU  " experiment,the back to experiments link is not present in the page instead the back to experiments link should be displayed on the screen in-order to view the list of experiments by the user.

Actual Result :
In the "Single Cycle MIPS CPU  " experiment,the back to experiments link is not present in the page.

Environment :
OS:Linux
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-organization-iiith/blob/master/test-cases/integration_test-cases/Single%20Cycle%20MIPS%20CPU/Single%20Cycle%20MIPS%20CPU_12_Back%20to%20experiment_smk.org

Attachment:
![cso48](https://cloud.githubusercontent.com/assets/14869397/14776594/175af0a2-0ae5-11e6-8364-53bee5f5edc9.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Issue is closed.
