### ISSUE TITLE
QA_Representation of Integers and their Arithmetic_Experiment_smk

### ISSUE THREAD

**Issue by kolliSuman** [virtual-labs/computer-organization-iiith#51]
Defect Description :
In the Experiment page of " Representation of Integers and their Arithmetic " experiment, when we click on the “Click here” link, a pop-up box with the download options is displaying on the screen instead it should redirect to the simulation page in-order to perform the simulation for the experiment

Actual Result :
In the Experiment page of " Representation of Integers and their Arithmetic " experiment, when we click on the “Click here” link, a pop-up box with the download options is displaying on the screen

Environment :
OS:Linux 
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-organization-iiith/blob/master/test-cases/integration_test-cases/Representation%20of%20Integers%20and%20their%20Arithmetic/Representation%20of%20Integers%20and%20their%20Arithmetic_07_Experiment_smk.org

Attachment:
![cso2](https://cloud.githubusercontent.com/assets/14869397/14779153/58066870-0af4-11e6-8339-022a94480430.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Closing the issue.
