### ISSUE TITLE
QA_Single Cycle MIPS CPU_Feedback_smk

### ISSUE THREAD

**Issue by kolliSuman** [virtual-labs/computer-organization-iiith#6]
Defect Description :
When we click on the feedback link in the feedback page of "Single Cycle MIPS CPU" experiment, it is redirecting to an error page(404) instead it should redirect to the feedback page.

Actual Result :
When we click on the feedback link of "Single Cycle MIPS CPU" experiment, it is redirecting to an error page(404).

Environment :
OS:Linux
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0Bandwidth : 100Mbps
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM ,
Processor:i5

 Test Step Link:
https://github.com/Virtual-Labs/computer-organization-iiith/blob/master/test-cases/integration_test-cases/Single%20Cycle%20MIPS%20CPU/Single%20Cycle%20MIPS%20CPU_10_Feedback_smk.org

Attachment:
![cso47](https://cloud.githubusercontent.com/assets/14869397/14776606/2332436c-0ae5-11e6-944d-e4573ece64fa.png)

**Comment by sravanthimodepu** [comment]
Issue is fixed now.

**Comment by BSravanthi** [comment]
Issue is closed.
